### ISSUE TITLE
freezed when patching arm11

### ISSUE THREAD

**Issue by stamosmats** [Mrrraou/waithax#18]
I've been following the steps with the new 3dsguide, got to the homebrew launcher via soundhax, and launched safehax. I waited fand after a while "Patching ARM11...". It has been there for over an hour and i don't know if it is safe to reboot my console
Running 11.0 o3dsxl

**Comment by jaxrogers2** [comment]
It's fine to power off/reboot your console. According to the Plailect Guide: "The linked version of waithax [the current release of waithax on this repo] is incompatible with safehax. This should be fixed soon, just give it time."

**Comment by Mrrraou** [comment]
there's no k11 code patching in this repo. this may be added at some point to properly reimplement svc0x7b when i'll get some time though. you may want to report this issue on @TiniVi's fork instead.
