### ISSUE TITLE
Optimization

### ISSUE THREAD

**Issue by codeHusky** [Mrrraou/waithax#3]
Take the distance we are from the overflow of the refcount, and use that to incrementally control our speed depending on how far we are from truly pushing over the edge of the counter to zero. By doing this, we can run at max speed for longer. Use while() loops rather than for loops, and do some on-the-fly calculations inside of the loop until we're done?

**Comment by codeHusky** [comment]
Probably by using a version of PID (as in proportional integral derivative)

**Comment by Mrrraou** [comment]
what you're saying makes no sense.

**Comment by codeHusky** [comment]
Instead of in the second stage of the overflow where we increment by one every time, we could instead dynamically determine how far we have to go and just go that much further once, reducing a few calls

**Comment by Mrrraou** [comment]
barely helps. you'd only get less than a second of optimization for the whole process. pointless.

**Comment by codeHusky** [comment]
true, yeah. I had this idea before I even ran it on actual hardware.

**Comment by Mrrraou** [comment]
i tried optimizing as best as i could. if you don't know how it works, i don't think you should try to give tips about it, really
