### ISSUE TITLE
Crash in PM when rebooting the console / in ret2hbmenu

### ISSUE THREAD

**Issue by Mrrraou** [Mrrraou/waithax#4]
Known issue. Due to some invalid handle or a corrupted KObjectLink.

**Comment by Mrrraou** [comment]
Fixed in latest commit.

**Comment by martinnnnnnnnnnnnnnnnnnn** [comment]
Is this the fix you mentioned?

**Comment by Mrrraou** [comment]
I didn't mention the fix for this issue anywhere else than here, afaik.

**Comment by martinnnnnnnnnnnnnnnnnnn** [comment]
Oh, alright. I was thinking of the one you said you were going to add in ~20 minutes from https://github.com/Mrrraou/FBI/commit/77924e64e46b65353b2fc3965a9b18f9d052ba21 .

**Comment by Mrrraou** [comment]
Check [this](https://www.reddit.com/r/3dshacks/comments/5hq202/working_dsiwarehax_installer_with_waithax/db4aqdu/) for more info. That's what I was talking about.
