### ISSUE TITLE
[Feature Request] Print current ETA every ~15 lines or so

### ISSUE THREAD

**Issue by dewiniaid** [Mrrraou/waithax#9]
There's plenty of ways to calculate how much time is left, but it seems (says the person who knows nothing about hacking on a 3DS) like this should be a fairly trivial addition.

I'm guesstimating 15 lines on the idea of ensuring that at least one ETA line is visible on the screen.

Since the timing seems to be fairly fixed, the timing algorithm wouldn't need to be particularly complicated - `(time_now - time_at_last_print) / iterations_per_print * remaining_iterations)` should suffice.

Additionally, it'd provide some interesting diagnostic data: it'd be much faster to determine if Waithax is running at N3DS speed or not, and you could tell if the reports of it taking an hour and 40 minutes were in fact that long (as well as whether the process was slowing down or just started that slow -- the former would cause ETA to go up)

(Aside: does the ARM11 do any sort of thermal throttling?  I've never felt my DS get warm before though.)

**Comment by Mrrraou** [comment]
Implemented in latest build
